defmodule Learning.Repo.Migrations.CreateKpayAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:kpay_accounts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:phone, :text, null: false)
      add(:balance, :bigint, null: false, default: 0)
    end
  end

  def down do
    drop(table(:kpay_accounts))
  end
end
