defmodule Learning.Repo.Migrations.InitialCoreBankingSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:Kpay_banks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:bic_code, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:Kpay_banks, [:bic_code], name: "Kpay_banks_unique_bank_index"))

    create table(:kpay_accounts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:phone, :text)
      add(:balance, :bigint, null: false, default: 0)
      add(:wallet_id, :uuid)
    end

    create(unique_index(:kpay_accounts, [:phone], name: "kpay_accounts_unique_account_index"))

    alter table(:kpay_accounts) do
      add(:bank_tenant_id, :uuid)
    end

    create table(:kpay_bank_tenants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:kpay_accounts) do
      modify(
        :bank_tenant_id,
        references(:kpay_bank_tenants,
          column: :id,
          name: "kpay_accounts_bank_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:kpay_bank_tenants) do
      add(:slug, :text, null: false)
      add(:status, :text, null: false, default: "active")

      add(
        :bank_id,
        references(:Kpay_banks,
          column: :id,
          name: "kpay_bank_tenants_bank_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(unique_index(:kpay_bank_tenants, [:slug], name: "kpay_bank_tenants_unique_slug_index"))

    create table(:kpay_transactions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:amount, :bigint, null: false)
      add(:status, :text, null: false, default: "pending")

      add(
        :from_account_id,
        references(:kpay_accounts,
          column: :id,
          name: "kpay_transactions_from_account_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :to_account_id,
        references(:kpay_accounts,
          column: :id,
          name: "kpay_transactions_to_account_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:kpay_wallets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:kpay_accounts) do
      modify(
        :wallet_id,
        references(:kpay_wallets,
          column: :id,
          name: "kpay_accounts_wallet_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:kpay_wallets) do
      add(:currency, :text, default: "XOF")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :bank_tenant_id,
        references(:kpay_bank_tenants,
          column: :id,
          name: "kpay_wallets_bank_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:kpay_wallets, "kpay_wallets_bank_tenant_id_fkey"))

    alter table(:kpay_wallets) do
      remove(:bank_tenant_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:currency)
    end

    drop(constraint(:kpay_accounts, "kpay_accounts_bank_tenant_id_fkey"))

    drop(constraint(:kpay_accounts, "kpay_accounts_wallet_id_fkey"))

    alter table(:kpay_accounts) do
      modify(:wallet_id, :uuid)
    end

    drop(table(:kpay_wallets))

    drop(constraint(:kpay_transactions, "kpay_transactions_to_account_id_fkey"))

    drop(constraint(:kpay_transactions, "kpay_transactions_from_account_id_fkey"))

    drop(table(:kpay_transactions))

    drop(constraint(:kpay_bank_tenants, "kpay_bank_tenants_bank_id_fkey"))

    drop_if_exists(
      unique_index(:kpay_bank_tenants, [:slug], name: "kpay_bank_tenants_unique_slug_index")
    )

    alter table(:kpay_bank_tenants) do
      remove(:bank_id)
      remove(:status)
      remove(:slug)
    end

    alter table(:kpay_accounts) do
      modify(:bank_tenant_id, :uuid)
    end

    drop(table(:kpay_bank_tenants))

    alter table(:kpay_accounts) do
      remove(:bank_tenant_id)
    end

    drop_if_exists(
      unique_index(:kpay_accounts, [:phone], name: "kpay_accounts_unique_account_index")
    )

    drop(table(:kpay_accounts))

    drop_if_exists(unique_index(:Kpay_banks, [:bic_code], name: "Kpay_banks_unique_bank_index"))

    drop(table(:Kpay_banks))
  end
end
