defmodule Learning.Repo.Migrations.CreateKpayBankingTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:Kpay_banks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:bic_code, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:kpay_bank_tenants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:slug, :text, null: false)
      add(:status, :text, null: false)

      add(
        :bank_id,
        references(:Kpay_banks,
          column: :id,
          name: "kpay_bank_tenants_bank_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:kpay_bank_tenants, "kpay_bank_tenants_bank_id_fkey"))

    drop(table(:kpay_bank_tenants))

    drop(table(:Kpay_banks))
  end
end
