defmodule Learning.Repo.Migrations.FixTransactionKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint("pkay_transactions", "pkay_transactions_pkey"))

    execute("ALTER TABLE \"pkay_transactions\" ADD PRIMARY KEY (id)")

    alter table(:pkay_transactions) do
      modify(:from_account_id, :uuid)
      modify(:to_account_id, :uuid)
    end
  end

  def down do
    alter table(:pkay_transactions) do
      modify(:to_account_id, :uuid)
      modify(:from_account_id, :uuid)
    end

    execute("ALTER TABLE \"pkay_transactions\" DROP constraint pkay_transactions_pkey")

    execute(
      "ALTER TABLE \"pkay_transactions\" ADD PRIMARY KEY (id, from_account_id, to_account_id)"
    )
  end
end
