defmodule Learning.Repo.Migrations.CreateKpayTransactionsa do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pkay_transactions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:amount, :bigint, null: false)
      add(:status, :text, null: false, default: "pending")

      add(
        :from_account_id,
        references(:kpay_accounts,
          column: :id,
          name: "pkay_transactions_from_account_id_fkey",
          type: :uuid,
          prefix: "public"
        ), primary_key: true, null: false)

      add(
        :to_account_id,
        references(:kpay_accounts,
          column: :id,
          name: "pkay_transactions_to_account_id_fkey",
          type: :uuid,
          prefix: "public"
        ), primary_key: true, null: false)
    end
  end

  def down do
    drop(constraint(:pkay_transactions, "pkay_transactions_to_account_id_fkey"))

    drop(constraint(:pkay_transactions, "pkay_transactions_from_account_id_fkey"))

    drop(table(:pkay_transactions))
  end
end
